package Steps;

import base.BaseUtil;
import cucumber.api.DataTable;
import cucumber.api.java.en.And;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import org.picocontainer.classname.ClassName;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Package: PACKAGE_NAME Generated by: Hoang.Son.Nguyen Generated at: 10.03.2018 2018
 * http://www.executeautomation.com/demosite/index.html?UserName=test&Password=test&Login=Login
 */
public class Login extends BaseUtil {
  private BaseUtil base;
  private static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());
  // test

  public Login(BaseUtil base) {
    this.base = base;
  }

  @Given("^i navigate to the login page$")
  public void navigatToLoginPage() throws Throwable {
    LOGGER.log(Level.FINER, "Ich bin von Given Logger", ClassName.class.getName().toString());
    System.out.println("Bin StepInfo: " + base.stepInfo);
    // throw new PendingException();
  }

  @And("^i enter the ([^\"]*) and ([^\"]*)$")
  public void iEnterTheUsernameAsAndPwdAs(String unsername, String pwd) throws Throwable {
    System.out.println("Pwd und Name" + unsername + " " + pwd);
    // throw new PendingException();
  }

  @And("^i click the Enter button$")
  public void iClickTheEnterButton() throws Throwable {
    System.out.println("Bin StepStatus:" + base.stepStatus);
    System.out.println("bin von Add2");
    // throw new PendingException();
  }

  @Then("^i could see the user form page$")
  public void iCouldSeeTherUserFormPage() throws Throwable {
    System.out.println("bin von Then");
    // throw new PendingException();
  }

  /* @And("^i enter the username and pwd$")
  public void iEnterTheUserDataTable(DataTable table) throws Throwable {
      // Write code here that turns the phrase above into concrete actions
      List<List<String>> data = table.raw();
      // Username = data.get(1).get(0)
      // Pwd = data.get(1)get()1;
      List<User> users = new ArrayList<User>();
      users = table.asList(User.class);
      for(User user : users){
          System.out.println(user.username + " " +user.pwd);
      }

  }*/

  @And("^i enter the c and ([^\"]*)$")
  public void iEnterTheUsernameAndPwd(String username, String pwd) throws Throwable {
    System.out.println(username + " " + pwd);
  }

  @And("^enter the username and pwd$")
  public void enterTheUsernameAndPwd(DataTable table) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    // List<List<String>> data = table.raw();
    // Username = data.get(1).get(0)
    // Pwd = data.get(1)get()1;
    List<User> users;
    users = table.asList(User.class);
    for (User user : users) {
      System.out.println(user.username + " " + user.pwd);
    }
  }

  public class User {
    public String username;
    public String pwd;

    public User(String username, String pwd) {
      this.username = username;
      this.pwd = pwd;
    }
  }
}
