package Steps;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 21.10.2018 2018
 */
@RunWith(Cucumber.class)
@CucumberOptions(
        features = "src//test//java//features//wiener",
        glue = {"Steps"},
        plugin = {"pretty", "json:target/cucumber-reports/Cucumber.json",
                "junit:target/cucumber-reports/Cucumber.xml",
                "html:target/cucumber-reports"},
        tags = ("@chrome, @firefox"),
        monochrome = true)
public class runAsJuniTest {
}
