package Steps.wiener;

import Steps.arrange.DriverWait;
import Steps.wiener.PageFactory.PFHelper;
import Steps.wiener.PageFactory.WienerWohnenHP;
import Steps.wiener.PageFactory.WohnberatungHP;
import base.BaseUtil;
import cucumber.api.java8.En;
import org.openqa.selenium.support.PageFactory;

/** Package: Steps.wiener Generated by: Hoang.Son.Nguyen Generated at: 28.10.2018 2018 */
public class NavigateToGemeindeWohnung extends BaseUtil implements En {
  private BaseUtil base;
  private WienerWohnenHP wiener_hp;

  public NavigateToGemeindeWohnung(BaseUtil base) {
    this.base = base;

    Given(
        "^ich navigiere zu wiener wohnen$",
        () -> {
          base.webDriver.navigate().to("https://www.wienerwohnen.at/");
          wiener_hp = PageFactory.initElements(base.webDriver, WienerWohnenHP.class);
          wiener_hp.hp_Logo_check();
          wiener_hp.interessantIn_check();
          wiener_hp.impresium_check();
        });
    And(
        "^ich klicke auf InteressentIn$",
        () -> {
          wiener_hp.interessantIn_click();
          wiener_hp.setGemeinWohnung_check();
        });
    When(
        "^ich klicke auf Gemeindewohnung$",
        () -> {
          wiener_hp.GemeinWohnung_click();
          wiener_hp.gemeinTitel_check();
        });
    And(
        "^ich klicke auf Wohnberatung Wien$",
        () -> {
          wiener_hp.wohnberatungWien_check();
          DriverWait.waitForSecondsTimeOut(3, base.webDriver);
          wiener_hp.WohnberatungWien_click();
          PFHelper.threatSleep(1000);
        });
    Then(
        "^ich sehe Seite von Gemeindewohnung$",
        () -> {
          wiener_hp.gemeinWohnungHP_check();
        });
    And(
        "^ich switch zu parent seite$",
        () -> {
          base.webDriver = PFHelper.switchToLastChildWindows(base.webDriver);
          WohnberatungHP wohnberatungHP =
              PageFactory.initElements(base.webDriver, WohnberatungHP.class);
          try {
            PFHelper.waitForSeconds(1);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
          wohnberatungHP.WohnberatungLogo_check();
          base.webDriver.switchTo().defaultContent();
        });
  }
}
