package Steps.wiener;

import Steps.wiener.PageFactory.PFHelper;
import base.BaseUtil;
import cucumber.api.java8.En;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebElement;

/** Package: Steps.wiener Generated by: Hoang.Son.Nguyen Generated at: 12.11.2018 2018 */
public class WohnberatungReg_Alert extends BaseUtil implements En {
  private BaseUtil base;
  private WebElement registrierung;
  private WebElement regButton;

  public WohnberatungReg_Alert(BaseUtil base) {
    this.base = base;

    Given(
        "^ich navigiere zu Loginseite von Wohnberatung Wien$",
        () -> {
          base.webDriver.navigate().to("https://wohnungssuche.wohnberatung-wien.at/");

          registrierung =
              this.base.webDriver.findElement(By.xpath("//a[contains(text(),'Registrierung')]"));
        });

    When(
        "^ich klicke auf Registrierung link$",
        () -> {
          registrierung.click();
          PFHelper.waitForSecondsTimeOut(3, this.base.webDriver);
          regButton =
              this.base.webDriver.findElement(
                  By.xpath("//button[@class='g-recaptcha form-field btn btn-primary btn-lg']"));
          // scroll
          JavascriptExecutor js = (JavascriptExecutor) this.base.webDriver;
          js.executeScript("window.scrollBy(0,1000)");
        });

    Then(
        "^ich klicke auf Registrieren Button$",
        () -> {
          regButton.click();
          try {
            PFHelper.waitForSeconds(3);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
        });
    And("^Alert mit Registrierungsfehlermeldung erscheint$", () -> {});
  }
}
