package Steps.wiener;

import Steps.wiener.PageFactory.PFHelper;
import Steps.wiener.PageFactory.WohnberatungHP;
import base.BaseUtil;
import cucumber.api.java8.En;
import org.openqa.selenium.support.PageFactory;

/** Package: Steps.wiener Generated by: Hoang.Son.Nguyen Generated at: 06.11.2018 2018 */
public class Wohnberatung_HP extends BaseUtil implements En {
  private BaseUtil base;
  private WohnberatungHP wohnberatungHP;

  public Wohnberatung_HP(BaseUtil base) {
    this.base = base;

    Given(
        "^ich navigiere zu wohnberatung-wien$",
        () -> {
          base.webDriver.navigate().to("https://www.wohnberatung-wien.at/");
          wohnberatungHP = PageFactory.initElements(base.webDriver, WohnberatungHP.class);
          try {
            PFHelper.waitForSeconds(2);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
          wohnberatungHP.WohnberatungLogo_check();
        });
    And(
        "^ich klicke auf wiener Wohn-Ticket$",
        () -> {
          wohnberatungHP.wohnticket_check();
          wohnberatungHP.wohnticket_click();
        });

    And(
        "^ich sehe den Inhalt des Popups$",
        () -> {
          wohnberatungHP.dropdown_open_check();
          wohnberatungHP.allgemeines_check();
          wohnberatungHP.wohnberatung_check();
          wohnberatungHP.wohnberatung_click();
          wohnberatungHP.wohnungsuche_check();
          wohnberatungHP.wohnungsuche_click();
          wohnberatungHP.wohnticket_click();
        });

    When(
        "^ich halte den Cursor über Allgemeines$",
        () -> {
          wohnberatungHP.allgemeines_tooltip_check();
        });

    Then("^ich sehe den ToolTipText Allgemeinse$", () -> {});
    When(
        "^ich klicke auf Allgemeines$",
        () -> {
          wohnberatungHP.allgemeines_click();
        });
    Then(
        "^ich sehe Allgemeinesseite$",
        () -> {
          // Write code here that turns the phrase above into concrete actions
          wohnberatungHP.AllgemeinesSiteTitel_check();
        });
    And(
        "^ich ziehe das Logo zu Login$",
        () -> {
          wohnberatungHP.dragLogoDropLogin();
          wohnberatungHP.wohnberatungLogo_click();
        });
    And(
        "^ich lasse die Links checken$",
        () -> {
          wohnberatungHP.allLinks_check();
        });
  }
}
