package Steps.hooks;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.picocontainer.classname.ClassName;

import java.io.File;
import java.util.logging.Logger;

/**
 * Package: Steps.hooks
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 04.11.2018 2018
 */
public class UtilityScreenshot {
    private static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());
    public static void CaptureScreenshot(WebDriver webDriver, String screeenshotName){
        try {
            TakesScreenshot ts = (TakesScreenshot) webDriver;
            File screenSource = ts.getScreenshotAs(OutputType.FILE);
            FileUtils.copyFile(screenSource, new File(".\\target\\screenshots\\"+screeenshotName+".png"));
        }catch (Exception ex){
            LOGGER.info("Screenshots trouble: "+ex.getMessage());
        }
    }
}
