package Steps.arrange;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.ie.InternetExplorerDriver;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.util.logging.Logger;

import static org.openqa.selenium.remote.BrowserType.*;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.04.2018 2018
 */

public class OpenCloseSite {


    static WebDriver webDriver;
    private static final Logger myLogger = Logger.getLogger("");

    private static void siteMaximize() {
        webDriver.manage().window().maximize();
    }

    public static void openSiteByUrl(String url, String browser) {
        //as default
        webDriver = startWebdriver(browser);
        siteMaximize();
        webDriver.get(url);
    }

    public static WebDriver startWebdriver(String browser) {
        switch (browser) {
            case FIREFOX:
                webDriver = new FirefoxDriver();
                break;
            case EDGE:
                webDriver = new EdgeDriver();
                break;
            case IE:
                webDriver = new InternetExplorerDriver();
                break;
            case CHROME:
                webDriver = new ChromeDriver();
        }
        return webDriver;

    }

    public static void closeSite() {
        myLogger.info(webDriver.getCurrentUrl() + " will be closed!");
        webDriver.close();
    }
}
