package Steps.tutor.pageFactory;

import Steps.wiener.PageFactory.PFHelper;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.picocontainer.classname.ClassName;

import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Logger;

import static org.testng.Assert.assertTrue;

/** Package: Steps.fileUpload Generated by: Hoang.Son.Nguyen Generated at: 17.11.2018 2018 */
public class FileUploadPageFactory {
  private WebDriver driver;
  private static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());

  public FileUploadPageFactory(WebDriver driver) {
    this.driver = driver;
  }

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//input[@type='file']")
  private WebElement dateiAuswaehlen;

  public void dateiAuswaehlen_click() {
    dateiAuswaehlen.click();
    PFHelper.threatSleep(1000);
  }

  public void ladeFile() throws AWTException {
    String projectLocation = System.getProperty("user.dir");
    StringSelection fileLocation =
        new StringSelection(projectLocation + "\\target\\cucumber-reports\\Cucumber.xml");
    Toolkit.getDefaultToolkit().getSystemClipboard().setContents(fileLocation, null);

    // imitate mouse events like ENTER, CTRL+C, CTRL+V
    Robot robot = new Robot();
    robot.keyPress(KeyEvent.VK_ENTER);
    robot.keyRelease(KeyEvent.VK_ENTER);
    robot.keyPress(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_V);
    robot.keyRelease(KeyEvent.VK_V);
    PFHelper.threatSleep(2000);
    robot.keyRelease(KeyEvent.VK_CONTROL);
    robot.keyPress(KeyEvent.VK_ENTER);
    robot.keyRelease(KeyEvent.VK_ENTER);
    PFHelper.threatSleep(3000);
  }

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//a[@class='button primary']")
  WebElement upDownloadButton;

  public void upLoadResult_check() {
    PFHelper.threatSleep(2000);
    assertTrue(upDownloadButton.isEnabled());
    // String uploadResult = upDownloadButton.getText();
    // assertTrue(uploadResult.toLowerCase().contains("cucumber.xml".toLowerCase()));
  }

  public void upDownloadButton_click() {
    upDownloadButton.click();
    // Alert accept
    PFHelper.threatSleep(2000);
  }

  Path path;

  public void fileExist_check() {
    path = Paths.get("C:\\Users\\Hoang.Son.Nguyen\\Desktop\\cucumber.xml");
    assertTrue(Files.exists(path));
  }

  public void fileDelete() {
    (new File(String.valueOf(path))).delete();
  }
}
