package Steps.tutor.pageFactory;

import org.openqa.selenium.WebDriver;
import org.picocontainer.classname.ClassName;

import java.util.logging.Logger;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 18.11.2018 2018 */
public class PageFactorySuperClass {
  public WebDriver driver;
  private static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());

  public PageFactorySuperClass(WebDriver driver) {
    this.driver = driver;
  }
}
