package Steps.tutor.pageFactory;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

/** Package: Steps.tutor.pageFactory Generated by: Hoang.Son.Nguyen Generated at: 27.11.2018 2018 */
public class PropertiesFileReader {

  public static String getValue(String key) throws IOException {
    final String propFilePath = "/Users/hnguyen/JavaTutor/Cucumber/src/test/configs/Confuguration.properties";
    BufferedReader reader = new BufferedReader(new FileReader(propFilePath));
    Properties prop = new Properties();
    prop.load(reader);
    reader.close();
    return prop.getProperty(key);
  }
}
