package Steps.tutor.pageFactory;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import java.util.Properties;

/** Package: Steps.tutor.pageFactory Generated by: Hoang.Son.Nguyen Generated at: 27.11.2018 2018 */
public class SendTestReportAsEmail {
  private class SMTPAuthenticator extends Authenticator {
    private PasswordAuthentication authentication;

    public SMTPAuthenticator(String login, String password) {
      authentication = new PasswordAuthentication(login, password);
    }

    @Override
    protected PasswordAuthentication getPasswordAuthentication() {
      return authentication;
    }
  }

  public void sendEmail() {
    // Recipient's email ID needs to be mentioned.
    String to = "hoangson.n@gmail.com";
    // Sender's email ID needs to be mentioned
    String from = "web@gmail.com";
    // Assuming you are sending email from localhost
    String host = "smtp.gmail.com";
    String port = "587";
    // Get system properties
    Properties properties = System.getProperties();
    // Setup mail server
    properties.setProperty("mail.smtp.host", host);
    properties.setProperty("mail.smtp.port", port);
    properties.setProperty("mail.smtp.auth", "true");
    properties.setProperty("mail.smtp.starttls.enable", "true");
    Authenticator auth = new SMTPAuthenticator("hoangson.n@gmail.com", "nguyen*1970");
    // Get the default Session object.
    Session session = Session.getInstance(properties, auth);

    try {
      // Create a default MimeMessage object.
      MimeMessage message = new MimeMessage(session);
      // Set From: header field of the header.
      try {
        message.setFrom(new InternetAddress(from));
      } catch (MessagingException e) {
        e.printStackTrace();
      }
      // Set To: header field of the header.
      message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

      // Set Subject: header field
      message.setSubject("Test result from run:");

      // Create the message part
      BodyPart messageBodyPart = new MimeBodyPart();

      // Fill the message
      messageBodyPart.setText("This is message body");

      // Create a multipar message
      Multipart multipart = new MimeMultipart();

      // Set text message part
      multipart.addBodyPart(messageBodyPart);

      // Part two is attachment
      messageBodyPart = new MimeBodyPart();
      String filename = ".\\target\\cucumber-reports\\index.html";
      DataSource source = new FileDataSource(filename);
      messageBodyPart.setDataHandler(new DataHandler(source));
      messageBodyPart.setFileName(filename);
      multipart.addBodyPart(messageBodyPart);

      // Send the complete message parts
      message.setContent(multipart);

      // Send message
      Transport.send(message);
      System.out.println("Sent message successfully....");
    } catch (MessagingException mex) {
      mex.printStackTrace();
    }
  }
}
