package Steps.tutor.pageFactory;

import org.openqa.selenium.WebDriver;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 18.11.2018 2018 */
public class WindowAutPageFactory extends PageFactorySuperClass {

  public WindowAutPageFactory(WebDriver driver) {
    super(driver);
  }

  public void switschToWinAuth() {
    // PFHelper.threatSleep(6000);
  }
}
