package Steps.wiener.PageFactory;

import org.junit.rules.ErrorCollector;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.CacheLookup;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.How;
import org.picocontainer.classname.ClassName;

import java.util.List;
import java.util.logging.Logger;

/**
 * Package: Steps.wiener.PageFactory Generated by: Hoang.Son.Nguyen Generated at: 06.11.2018 2018
 */
public class WohnberatungHP {
  private WebDriver driver;
  private static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());
  ErrorCollector errorCollector = new ErrorCollector();

  public WohnberatungHP(WebDriver driver) {
    this.driver = driver;
  }

  @FindBy(how = How.XPATH, using = "//img[@class='navbar-brand-logo-normal']")
  @CacheLookup
  WebElement wohnberatungLogo;

  public void WohnberatungLogo_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        wohnberatungLogo,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
    wohnberatungLogo_rightclick();
  }
  public void wohnberatungLogo_click(){
    wohnberatungLogo.click();
  }

  /*
   * Webdriver, WebElement and the Count of element in context to click
   * */
  public void wohnberatungLogo_rightclick() {
    PFHelper.webElementRightClick_ContextClick(driver, wohnberatungLogo, 11);
  }

  @FindBy(
      how = How.XPATH,
      using =
          "//body[@id='p1']/div[@class='body-bg body-bg-top']/header[@class='navbar navbar-default navbar-has-image navbar-top navbar-fixed-top']/div[@class='container']/div[@class='row']/nav[@class='navbar-collapse collapse']/ul[@class='nav navbar-nav navbar-main']/li[1]/a[1]")
  @CacheLookup
  WebElement wohnTicket;

  public void wohnticket_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        wohnTicket,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  public void wohnticket_click() {
    wohnTicket.click();
  }

  @FindBy(how = How.XPATH, using = "//a[@title='Allgemeines']")
  @CacheLookup
  WebElement allgemeines;

  public void allgemeines_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        allgemeines,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  public void allgemeines_click() {
    allgemeines.click();
    PFHelper.threatSleep(2000);
  }

  @FindBy(how = How.XPATH, using = "//span[contains(text(),'Allgemeines')]")
  @CacheLookup
  WebElement allgemeinesTooltip;

  public void allgemeines_tooltip_check() {
    Actions action = new Actions(driver);
    action.moveToElement(allgemeines).build().perform();
    PFHelper.string_check(driver, allgemeinesTooltip, allgemeinesTooltip.getText(), "Allgemeines");
  }

  @FindBy(how = How.XPATH, using = "//li[@class='dropdown open']//ul[@class='dropdown-menu']")
  @CacheLookup
  WebElement dropdown_open;

  public void dropdown_open_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        dropdown_open,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  @FindBy(
      how = How.XPATH,
      using =
          "//body[@id='p1']/div[@class='body-bg body-bg-top']/header[@class='navbar navbar-default navbar-has-image navbar-top navbar-fixed-top']/div[@class='container']/div[@class='row']/nav[@class='navbar-collapse collapse']/ul[@class='nav navbar-nav navbar-main']/li[2]/a[1]")
  @CacheLookup
  WebElement wohnberatung;

  public void wohnberatung_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        wohnberatung,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  public void wohnberatung_click() {
    wohnberatung.click();
  }

  @CacheLookup
  @FindBy(
      how = How.XPATH,
      using =
          "//body[@id='p1']/div[@class='body-bg body-bg-top']/header[@class='navbar navbar-default navbar-has-image navbar-top navbar-fixed-top']/div[@class='container']/div[@class='row']/nav[@class='navbar-collapse collapse']/ul[@class='nav navbar-nav navbar-main']/li[3]/a[1]")
  WebElement wohnungsuche;

  public void wohnungsuche_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        wohnungsuche,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  public void wohnungsuche_click() {
    wohnungsuche.click();
  }

  @FindBy(how = How.XPATH, using = "//h1[contains(@class,'element-header')]")
  @CacheLookup
  WebElement allgemeinesSiteTitel;

  public void AllgemeinesSiteTitel_check() {
    PFHelper.element_visible_enabled_check(
        driver,
        allgemeinesSiteTitel,
        this.getClass().getName(),
        new Object() {}.getClass().getEnclosingMethod().getName());
  }

  @CacheLookup
  @FindBy(
      how = How.XPATH,
      using = "//img[@src='/typo3conf/ext/wohnpartner/Resources/Public/Images/login.png']")
  WebElement wohnberatungloginButton;

  public void dragLogoDropLogin() {
    PFHelper.dragAndDrop(this.driver, wohnberatungLogo, wohnberatungloginButton);

  }

  @CacheLookup
  @FindBy(how = How.XPATH, using = "//a[@href]")
  List<WebElement> linklist;

  public void allLinks_check() {
    for (WebElement link : linklist) {
      PFHelper.verifyLinkActive(link.getAttribute("href"));
    }
  }
}
