package Steps.assertion;

import org.openqa.selenium.WebElement;

import static org.junit.Assert.assertTrue;

/** Package: Steps.assertion Generated by: Hoang.Son.Nguyen Generated at: 06.11.2018 2018 */
public class WebElementChecks {
  public static boolean displayed_enabled_check(WebElement webElement) {
    assertTrue(webElement.isDisplayed());
    assertTrue(webElement.isEnabled());
    if (!webElement.isDisplayed() || !webElement.isEnabled()) {
      return false;
    } else return true;
  }
}
