package Steps.gmxStep;

import Tranformation.EmailTranformation;
import base.BaseUtil;
import cucumber.api.Transform;
import cucumber.api.java8.En;

/**
 * Package: Steps
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 16.10.2018 2018
 */
public class GmxLoginOutlineStep extends BaseUtil implements En {
    private BaseUtil base;

    public GmxLoginOutlineStep(BaseUtil base) {
        this.base = base;

        And("^i enter to outline the  ([^\"]*) and ([^\"]*)$", (String username, String password) -> {
            System.out.println("Username: " + username + " pwd: " + password);
            System.out.println("Info from Hook over BaseUtil: " + base.stepInfo);
        });
        And("^i enter from outline the([^\"]*) and ([^\"]*) and ([^\"]*)$", (String Username, String Password, String Case) -> {
            System.out.println("Username: " + Username + " pwd: " + Password + " Case: " + Case);
        });
        When("^the Gmx site is opened$", () -> {
            // Write code here that turns the phrase above into concrete actions
            //throw new PendingException();
        });

        And("^i enter the contact email: ([^\"]*)$", (@Transform(EmailTranformation.class) String email) -> {
            System.out.println("transformaed email: " + email + "\n");
        });

        And("^i enter the alternative email ([^\"]*$)", (@Transform(EmailTranformation.class) String email) -> {
            System.out.println("transformaed email: " + email + "\n");

        });


    }
}
