package base;

import org.openqa.selenium.WebDriver;
import org.picocontainer.classname.ClassName;

import java.util.logging.Logger;

/**
 * Package: base
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 12.03.2018 2018
 */
public class BaseUtil {
    // Dient zum übertragen von Infos z.B. Webdriver von inistep zu step
    public String stepInfo;
    public String stepStatus;
    public static final Logger LOGGER = Logger.getLogger(ClassName.class.getName());

    // Selenium
    public WebDriver webDriver;
}
