/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 10.03.2018 2018
 * Tutorial: https://www.youtube.com/watch?v=5eezIEYqfCo&index=3&list=PL6tu16kXT9PpteusHGISu_lHcV6MbBtA6
 */
public class Main {
    public static void main(String[] args){
        //System.out.println("Hello die Welt, ich bin der Main");

    }
}
