package Steps.tutor;

import Steps.tutor.pageFactory.AlertHandlePageFactory;
import Steps.wiener.PageFactory.PFHelper;
import base.BaseUtil;
import cucumber.api.java8.En;
import org.openqa.selenium.support.PageFactory;

/** Package: PACKAGE_NAME Generated by: Hoang.Son.Nguyen Generated at: 19.11.2018 2018 */
public class AlertHandleSteps extends BaseUtil implements En {
  BaseUtil base;
  AlertHandlePageFactory alertHandlePageFactory;

  public AlertHandleSteps(BaseUtil base) {
    this.base = base;

    Given(
        "^ich navigiere zu artoftesting$",
        () -> {
          base.webDriver.navigate().to("https://artoftesting.com/sampleSiteForSelenium.html");
          PFHelper.threatSleep(1000);
          alertHandlePageFactory =
              PageFactory.initElements(base.webDriver, AlertHandlePageFactory.class);
        });
    And(
        "^ich sehe doubleclick to generate alert box$",
        () -> {
          alertHandlePageFactory.alertBoxBtn_check();
        });
    When(
        "^ich klicke auf alertBoxButton$",
        () -> {
          alertHandlePageFactory.submitClickJS();
          alertHandlePageFactory.hightlightTextBox();
          alertHandlePageFactory.alertBoxBtn_doubleClick();
        });
    Then(
        "^ich akzeptiere allert$",
        () -> {
          alertHandlePageFactory.alertAccept();
        });
    And(
        "^ich drag und drop Image$",
        () -> {
          alertHandlePageFactory.dragDropArtOfTest();
          PFHelper.threatSleep(1500);
        });
  }
}
