package Steps.tutor;

import Steps.tutor.pageFactory.CSVFileOps;
import base.BaseUtil;
import cucumber.api.java8.En;

import java.io.IOException;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 26.11.2018 2018 */
public class CsvOpsTestSteps extends BaseUtil implements En {
  BaseUtil base;

  public CsvOpsTestSteps(BaseUtil base) {
    this.base = base;
    Given(
        "^ich lese daten aus csvFile$",
        () -> {
          try {
            CSVFileOps.csvRead(".\\src\\test\\TestData\\csvTestData.csv");
          } catch (IOException e) {
            e.printStackTrace();
          }
        });

    When(
        "^ich schreibe daten in csvFile$",
        () -> {
          String[] dataToWrite = {"chin", "muoi", "muoi mot", "muoi hai"};
          try {
            CSVFileOps.csvWrite(".\\src\\test\\TestData\\csvTestData.csv", dataToWrite);
          } catch (IOException e) {
            e.printStackTrace();
          }
        });

    Then(
        "^ich kann die neue Daten in csvFile sehen$",
        () -> {
          try {
            CSVFileOps.csvRead(".\\src\\test\\TestData\\csvTestData.csv");
          } catch (IOException e) {
            e.printStackTrace();
          }
        });
  }
}
