package Steps.tutor;

import Steps.tutor.pageFactory.ExcelUtil;
import Steps.wiener.PageFactory.PFHelper;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 02.12.2018 2018 */
public class DdtDataProviderSimpleSteps {

  WebDriver driver;

  @BeforeTest
  public void beforeTestOpenThing() {
    // Open browsre
    driver = new ChromeDriver();

    // Maximize browser
    driver.manage().window().maximize();

    // Load application
    driver.get("http://www.facebook.com");
  }

  @Test(dataProvider = "dataProv")
  public void TestFireFox(String uname, String password) {

    // clear email field

    driver.findElement(By.id("email")).clear();

    // Enter usename
    driver.findElement(By.id("email")).sendKeys(uname);

    // Clear password field
    driver.findElement(By.id("pass")).clear();

    // Enter password
    driver.findElement(By.id("pass")).sendKeys(password);
    PFHelper.threatSleep(2000);
  }

  // this is DataProvider which actually feed data to our test cases here I have taken 2 D //array
  // with 2 rows and 2 column it means. It will run our test case two times because we //have taken
  // 2 rows. While first iteration this will pass username and password to test //case and in second
  // iteration perform the same for second rows
  @DataProvider(name = "dataProv")
  public Object[][] TestDataFeed() {

    // Create object array with 2 rows and 2 column- first parameter is row and second is //column
    Object[][] facebookdata = new Object[2][2];

    // Enter data to row 0 column 0
    facebookdata[0][0] = "Selenium1@gmail.com";

    // Enter data to row 0 column 1
    facebookdata[0][1] = "Password1";

    // Enter data to row 1 column 0
    facebookdata[1][0] = "Selenium2@gmail.com";

    // Enter data to row 1 column 0
    facebookdata[1][1] = "Password2";

    // return arrayobject to testscript

    ExcelUtil excelUtil = new ExcelUtil("src\\test\\TestData", "Tabelle2", "TestSheet.xlsx");
    System.out.println("olalalal: " + excelUtil.getCellData(1, 0));
    PFHelper.threatSleep(1000);
    Object[][] a = excelUtil.excelToArray();

    System.out.println(facebookdata.getClass().toString() + "  vs.   " + a.getClass());
    return facebookdata;
  }

  @AfterTest
  public void closeDriver() {
    driver.quit();
  }
}
