package Steps.tutor;

import Steps.tutor.pageFactory.ExcelFileTestSteps;
import Steps.tutor.pageFactory.ExcelUtil;
import base.BaseUtil;
import cucumber.api.java8.En;

import java.io.IOException;

/** Package: PACKAGE_NAME Generated by: Hoang.Son.Nguyen Generated at: 26.11.2018 2018 */
public class ExcelOpsSteps extends BaseUtil implements En {
  BaseUtil base;

  public ExcelOpsSteps(BaseUtil base) {
    this.base = base;
    Given(
        "^ich lese daten eines excelFile$",
        () -> {
          try {
            ExcelFileTestSteps.readExcel(".\\src\\test\\TestData", "TestSheet.xlsx", "Tabelle1");
          } catch (IOException e) {
            e.printStackTrace();
          }
        });
    When(
        "^ich schreibe eine neue zeile$",
        () -> {
          String[] dataToWrite = {"Hoang Minh", "Nguyen", "31.05,2015"};
          try {
            ExcelFileTestSteps.writeExcel(
                ".\\src\\test\\TestData", "TestSheet.xlsx", "Tabelle1", dataToWrite);
          } catch (IOException e) {
            e.printStackTrace();
          }
        });
    And(
        "^ich kann die neue Daten sehen$",
        () -> {
          try {
            ExcelFileTestSteps.readExcel(".\\src\\test\\TestData", "TestSheet.xlsx", "Tabelle1");
          } catch (IOException e) {
            e.printStackTrace();
          }
          ExcelUtil excelUtil = new ExcelUtil("src\\test\\TestData", "Tabelle2", "TestSheet.xlsx");
          excelUtil.excelToArray();
          System.out.println("hohoohohohohoho: " + excelUtil.getCellData(0, 2));
        });

    And(
        "^ich schreibe ([^\"]*)und ([^\"]*) und ([^\"]*)$",
        (String Vorname, String Nachname, String Geb) -> {
          String[] dataToWrite = {Vorname, Nachname, Geb};
          try {
            ExcelFileTestSteps.writeExcel(
                ".\\src\\test\\TestData", "TestSheet.xlsx", "Tabelle1", dataToWrite);
          } catch (IOException e) {
            e.printStackTrace();
          }
        });
  }
}
