package Steps.tutor;

import Steps.tutor.pageFactory.FileUploadPageFactory;
import Steps.wiener.PageFactory.PFHelper;
import base.BaseUtil;
import cucumber.api.java8.En;
import org.openqa.selenium.support.PageFactory;

import java.awt.*;

/** Package: Steps.fileUpload Generated by: Hoang.Son.Nguyen Generated at: 17.11.2018 2018 */
public class FileUploadSteps extends BaseUtil implements En {
  BaseUtil base;
  FileUploadPageFactory fileUploadPageFactory;

  public FileUploadSteps(BaseUtil base) {
    this.base = base;
    Given(
        "^ich navigiere zu tus io$",
        () -> {
          base.webDriver.navigate().to("https://tus.io/demo.html");
          fileUploadPageFactory =
              PageFactory.initElements(base.webDriver, FileUploadPageFactory.class);
        });
    And(
        "^ich klicke auf Datei auswählen$",
        () -> {
          fileUploadPageFactory.dateiAuswaehlen_click();
        });

    When(
        "^ich wähle Datei aus und lade hoch$",
        () -> {
          try {
            fileUploadPageFactory.ladeFile();
          } catch (AWTException e) {
            e.printStackTrace();
          }
        });

    Then(
        "^ich sehe die Erfolgmeldung$",
        () -> {
          fileUploadPageFactory.upLoadResult_check();
        });
    When(
        "^ich clicke auf geladene Datei$",
        () -> {
          fileUploadPageFactory.upDownloadButton_click();

          PFHelper.threatSleep(2000);
        });
    Then(
        "^ich sehe downloaded datei local$",
        () -> {
          fileUploadPageFactory.fileExist_check();
        });
    And(
        "^ich loesche die Datei$",
        () -> {
          fileUploadPageFactory.fileDelete();
        });
  }
}
