package Steps.tutor;

import base.BaseUtil;
import cucumber.api.java8.En;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 21.11.2018 2018 */
public class PopUpHandleSteps extends BaseUtil implements En {
  BaseUtil base;

  public PopUpHandleSteps(BaseUtil base) {
    this.base = base;
    Given(
        "^ich navigiere zu facebook$",
        () -> {
          base.webDriver.navigate().to("https://www.facebook.com");
        });
    And("^behandle das PopUp$", () -> {});
  }
}
