package Steps.tutor;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;

/** Package: Steps.tutor Generated by: Hoang.Son.Nguyen Generated at: 30.11.2018 2018 */

/** Preparing: Hub started, Node registed webdriver on Node generate with URL(if incl.) from NODE */
public class SeleninumGridTest {

  @Test
  public void runChromeRemote() throws MalformedURLException {
    this.executeTest(DesiredCapabilities.chrome());
  }

  private void executeTest(DesiredCapabilities capabilities) throws MalformedURLException {
    ChromeOptions chromeOptions = new ChromeOptions();
    // chromeOptions.addArguments("--headless");
    capabilities.setCapability(ChromeOptions.CAPABILITY, chromeOptions);
    WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4448/wd/hub"), capabilities);
    // driver = new RemoteWebDriver(new URL("http://172.17.0.2:4444/wd/hub"), capabilities);
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.navigate().to("https://www.javacodegeeks.com");
    driver.quit();
  }

  @Test
  public void runFirefoxRemote() throws MalformedURLException {

    FirefoxOptions firefoxOptions = new FirefoxOptions();
    // firefoxOptions.setCapability("marionette", true);
    // driver = new RemoteWebDriver(new URL("http://172.28.3.22:4449/wd/hub"), firefoxOptions);
    WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4448/wd/hub"), firefoxOptions);
    try {
      Thread.sleep(3000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.navigate().to("https://www.javacodegeeks.com");
    driver.quit();
  }

  @AfterTest
  public void stopTest() {}
}
