package Tranformation;

import cucumber.api.Transformer;
import cucumber.api.java.it.Date;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 * Package: Tranformation
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.10.2018 2018
 */
public class StringToDatetime extends Transformer<LocalDateTime> {


    @Override
    public LocalDateTime transform(String value) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return LocalDateTime.parse(value, formatter);
    }
}
