package Tranformation;

import javax.xml.transform.Result;

import cucumber.api.Transformer;

/**
 * Package: Tranformation
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 14.03.2018 2018
 */
public class toDigitTransformer extends Transformer<Integer> {

    @Override
    public Integer transform(String value) {

        return Integer.valueOf(value);
    }


}
